import {
  ActivityType,
  BookingSource,
  BookingStatus,
  DepositStatus,
  ScheduleAssignmentRole,
  ScheduleTimeSlot,
} from '../src/generated/prisma/enums';

import type { DemoBookingSeed } from './seed-types';

const markLead = {
  email: 'mark@diveshop.local',
  role: ScheduleAssignmentRole.LEAD_INSTRUCTOR,
};
const erikLead = {
  email: 'erik@diveshop.local',
  role: ScheduleAssignmentRole.LEAD_INSTRUCTOR,
};
const rigieGuide = {
  email: 'rigie@diveshop.local',
  role: ScheduleAssignmentRole.GUIDE,
};
const juniorDivemaster = {
  email: 'junior@diveshop.local',
  role: ScheduleAssignmentRole.DIVEMASTER,
};

export const demoBookings: DemoBookingSeed[] = [
  {
    key: 'returning-fun-diver-history', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.WHATSAPP, createdOffset: -22,
    notes: 'Hi again! I would love two morning dives while I am back on the island.', internalNotes: 'Returning guest. Requested Monad Shoal followed by Gato if conditions allow.', adminNotes: 'Approved; recent log and certification checked.',
    participants: [{ customerKey: 'sofia-reyes' }],
    activities: [{ key: 'fun-dives', activityType: ActivityType.FUN_DIVE, dateOffset: -18, requestedTime: '05:00', timeSlot: ScheduleTimeSlot.AM, notes: 'Two-tank fun dive.', assignments: [markLead, rigieGuide] }],
    deposit: { amount: 2500, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Front desk', paymentMethod: 'GCash', paidOffset: -21 },
  },
  {
    key: 'wechat-dsd-couple-history', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.WECHAT, createdOffset: -20,
    notes: '我们想体验潜水，两个人，都不会潜水。', internalNotes: 'Chinese-speaking couple; pool briefing before confined-water skills.', adminNotes: 'Medical questionnaires clear.',
    participants: [{ customerKey: 'chen-yu', equipmentNeeded: 'Full equipment, size M' }, { customerKey: 'zhang-min', equipmentNeeded: 'Full equipment, size S' }],
    activities: [{ key: 'dsd', activityType: ActivityType.DISCOVER_SCUBA_DIVING, dateOffset: -16, requestedTime: '08:30', timeSlot: ScheduleTimeSlot.AM, assignments: [erikLead, juniorDivemaster] }],
    deposit: { amount: 1000, status: DepositStatus.PAID, currency: 'YUAN', paidTo: 'WeChat Pay', paymentMethod: 'WeChat Pay', paidOffset: -19 },
  },
  {
    key: 'wilson-open-water-course', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.EMAIL, createdOffset: -20,
    notes: 'We completed the eLearning and would like to finish the course together.', internalNotes: 'Verify eLearning completion before first session.', adminNotes: 'Three-day course approved.',
    participants: [{ customerKey: 'emma-wilson', equipmentNeeded: 'Full equipment, size S' }, { customerKey: 'liam-wilson', equipmentNeeded: 'Full equipment, size L' }],
    activities: [{ key: 'open-water', activityType: ActivityType.OPEN_WATER_COURSE, dateOffset: -14, durationDays: 3, requestedTime: '08:00', timeSlot: ScheduleTimeSlot.AM, scheduleNotes: 'Confined skills day 1; open-water dives days 2–3.', assignments: [erikLead, juniorDivemaster] }],
    deposit: { amount: 8000, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Reception', paymentMethod: 'Card', paidOffset: -18 },
  },
  {
    key: 'international-fun-dive-group', status: BookingStatus.SCHEDULED, createdByEmail: 'manager@diveshop.local', source: BookingSource.WALK_IN, createdOffset: -14,
    notes: 'Three certified divers looking for a relaxed two-dive day.', internalNotes: 'Mixed experience; keep conservative profile.', adminNotes: 'Certification cards sighted.',
    participants: [{ customerKey: 'lucia-bianchi' }, { customerKey: 'noah-fischer' }, { customerKey: 'aisha-rahman' }],
    activities: [{ key: 'fun-dives', activityType: ActivityType.FUN_DIVE, dateOffset: -12, requestedTime: '07:00', timeSlot: ScheduleTimeSlot.AM, assignments: [markLead, rigieGuide] }],
    deposit: { amount: 4500, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Reception', paymentMethod: 'Cash', paidOffset: -14 },
  },
  {
    key: 'tan-advanced-course-history', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.REFERRAL, createdOffset: -16, referrerName: 'Sofia Reyes',
    notes: 'We want to take Advanced together and are especially interested in navigation.', internalNotes: 'Couple sharing one contact number.', adminNotes: 'Two-day course plan approved.',
    participants: [{ customerKey: 'daniel-tan' }, { customerKey: 'mei-lin-tan' }],
    activities: [{ key: 'advanced', activityType: ActivityType.ADVANCED_OPEN_WATER_COURSE, dateOffset: -10, durationDays: 2, requestedTime: '07:30', timeSlot: ScheduleTimeSlot.AM, assignments: [erikLead] }],
    deposit: { amount: 6000, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Front desk', paymentMethod: 'Card', paidOffset: -15 },
  },
  {
    key: 'sidemount-specialty-history', status: BookingStatus.SCHEDULED, createdByEmail: 'admin@diveshop.local', source: BookingSource.INSTRUCTOR, createdOffset: -13, referrerName: 'Mark Instructor',
    notes: 'Sidemount specialty with own harness.', internalNotes: 'Student owns harness; shop cylinders and regulators required.', adminNotes: 'Equipment configuration reviewed with instructor.',
    participants: [{ customerKey: 'haruto-sato', equipmentNeeded: 'Twin AL80 cylinders and two regulators' }],
    activities: [{ key: 'sidemount', activityType: ActivityType.SPECIALTY_COURSE, specialtyCourse: 'Sidemount Diver', dateOffset: -8, durationDays: 2, requestedTime: '08:00', timeSlot: ScheduleTimeSlot.AM, assignments: [markLead] }],
    deposit: { amount: 5000, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Mark Instructor', paymentMethod: 'Bank transfer', paidOffset: -12 },
  },
  {
    key: 'ong-family-snorkeling-history', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.WHATSAPP, createdOffset: -10,
    notes: 'Family of four, two adults and two confident teenage swimmers.', internalNotes: 'Life jackets requested for all guests.', adminNotes: 'Private guide arranged.',
    participants: [{ customerKey: 'grace-ong' }, { customerKey: 'kai-ong' }, { customerKey: 'ella-ong' }, { customerKey: 'tom-ong' }],
    activities: [{ key: 'snorkeling', activityType: ActivityType.SNORKELING, dateOffset: -6, requestedTime: '09:30', timeSlot: ScheduleTimeSlot.AM, assignments: [rigieGuide, juniorDivemaster] }],
    deposit: { amount: 2000, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Front desk', paymentMethod: 'Cash', paidOffset: -9 },
  },
  {
    key: 'scuba-review-history', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.EMAIL, createdOffset: -9,
    notes: 'I have not dived for over a year and would like a refresher before fun diving.', internalNotes: 'Pool refresher plus one easy shore dive.', adminNotes: 'Scuba Review approved.',
    participants: [{ customerKey: 'ben-carter' }],
    activities: [{ key: 'review', activityType: ActivityType.SCUBA_REVIEW, dateOffset: -4, requestedTime: '13:00', timeSlot: ScheduleTimeSlot.PM, assignments: [markLead] }],
    deposit: { amount: 1500, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Reception', paymentMethod: 'Card', paidOffset: -8 },
  },
  {
    key: 'recent-fun-dive', status: BookingStatus.SCHEDULED, createdByEmail: 'manager@diveshop.local', source: BookingSource.WALK_IN, createdOffset: -5,
    notes: 'Single afternoon dive after arrival.', internalNotes: 'Check current before selecting site.', adminNotes: 'Approved for afternoon boat.',
    participants: [{ customerKey: 'maria-garcia' }],
    activities: [{ key: 'fun-dive', activityType: ActivityType.FUN_DIVE, dateOffset: -2, requestedTime: '14:00', timeSlot: ScheduleTimeSlot.PM, assignments: [erikLead] }],
    deposit: { amount: 1800, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Reception', paymentMethod: 'Cash', paidOffset: -5 },
  },
  {
    key: 'today-fun-dive-group', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.WHATSAPP, createdOffset: -6,
    notes: 'Morning fun dives for three certified friends.', internalNotes: 'Jack requested 15 L cylinder.', adminNotes: 'Approved and equipment reserved.',
    participants: [{ customerKey: 'jack-thompson' }, { customerKey: 'priya-nair' }, { customerKey: 'yuki-nakamura' }],
    activities: [{ key: 'fun-dives', activityType: ActivityType.FUN_DIVE, dateOffset: 0, requestedTime: '05:00', timeSlot: ScheduleTimeSlot.AM, scheduleNotes: 'Monad departure; confirm weather at 04:30.', assignments: [markLead, rigieGuide] }],
    deposit: { amount: 4500, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Front desk', paymentMethod: 'Card', paidOffset: -5 },
  },
  {
    key: 'today-dsd-couple', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.WALK_IN, createdOffset: -2,
    notes: 'First-time divers, available this afternoon.', internalNotes: 'Allow extra time for briefing; both are comfortable swimmers.', adminNotes: 'Medical forms reviewed.',
    participants: [{ customerKey: 'olivia-martin', equipmentNeeded: 'Full equipment, size S' }, { customerKey: 'ethan-martin', equipmentNeeded: 'Full equipment, size M' }],
    activities: [{ key: 'dsd', activityType: ActivityType.DISCOVER_SCUBA_DIVING, dateOffset: 0, requestedTime: '13:30', timeSlot: ScheduleTimeSlot.PM, assignments: [erikLead, juniorDivemaster] }],
    deposit: { amount: 3500, status: DepositStatus.PARTIALLY_PAID, currency: 'PESOS', paidTo: 'Reception', paymentMethod: 'Cash', paidOffset: -2, notes: 'Balance due before equipment fitting.' },
  },
  {
    key: 'tomorrow-returning-fun-dive', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.WHATSAPP, createdOffset: -5,
    notes: 'Sofia is returning with Mateo for two dives tomorrow morning.', internalNotes: 'Returning guest history available; nitrox requested if available.', adminNotes: 'Complete booking scheduled for tomorrow.',
    participants: [{ customerKey: 'sofia-reyes' }, { customerKey: 'mateo-santos' }],
    activities: [{ key: 'fun-dives', activityType: ActivityType.FUN_DIVE, dateOffset: 1, requestedTime: '06:00', timeSlot: ScheduleTimeSlot.AM, scheduleNotes: 'Two tanks; nitrox requested for both divers.', assignments: [erikLead, rigieGuide] }],
    deposit: { amount: 4000, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Front desk', paymentMethod: 'GCash', paidOffset: -4 },
  },
  {
    key: 'upcoming-open-water-group', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.EMAIL, createdOffset: -7,
    notes: 'Three friends have completed eLearning and need the practical course.', internalNotes: 'Arrange three complete equipment sets.', adminNotes: 'Three-day course; instructor and DM assigned throughout.',
    participants: [{ customerKey: 'samir-patel', equipmentNeeded: 'Full equipment, size L' }, { customerKey: 'chloe-dubois', equipmentNeeded: 'Full equipment, size S' }, { customerKey: 'kai-ong', equipmentNeeded: 'Full equipment, size M' }],
    activities: [{ key: 'open-water', activityType: ActivityType.OPEN_WATER_COURSE, dateOffset: 2, durationDays: 3, requestedTime: '08:00', timeSlot: ScheduleTimeSlot.AM, scheduleNotes: 'Day 1 confined water; days 2–3 open water.', assignments: [markLead, juniorDivemaster] }],
    deposit: { amount: 9000, status: DepositStatus.PARTIALLY_PAID, currency: 'PESOS', paidTo: 'Reception', paymentMethod: 'Card', paidOffset: -6, notes: 'Remaining course balance due on day 1.' },
  },
  {
    key: 'night-diver-specialty', status: BookingStatus.SCHEDULED, createdByEmail: 'admin@diveshop.local', source: BookingSource.INSTRUCTOR, createdOffset: -4, referrerName: 'Tomas Instructor',
    notes: 'Night Diver specialty; customer has torch and DSMB.', internalNotes: 'Meet at shop before sunset.', adminNotes: 'Night slot confirmed.',
    participants: [{ customerKey: 'lucia-bianchi' }],
    activities: [{ key: 'night-diver', activityType: ActivityType.SPECIALTY_COURSE, specialtyCourse: 'Night Diver', dateOffset: 3, requestedTime: '18:00', timeSlot: ScheduleTimeSlot.NIGHT, assignments: [markLead] }],
    deposit: { amount: 2500, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Tomas Instructor', paymentMethod: 'Cash', paidOffset: -3 },
  },
  {
    key: 'busy-day-fun-group', status: BookingStatus.SCHEDULED, createdByEmail: 'manager@diveshop.local', source: BookingSource.REFERRAL, createdOffset: -5, referrerName: 'Ocean Vida Resort',
    notes: 'Hotel referral for four certified divers.', internalNotes: 'Split across two buddy pairs; mixed agencies.', adminNotes: 'Guide coverage confirmed.',
    participants: [{ customerKey: 'aisha-rahman' }, { customerKey: 'daniel-tan' }, { customerKey: 'mei-lin-tan' }, { customerKey: 'felix-muller' }],
    activities: [{ key: 'fun-dives', activityType: ActivityType.FUN_DIVE, dateOffset: 4, requestedTime: '06:30', timeSlot: ScheduleTimeSlot.AM, assignments: [erikLead, rigieGuide] }],
    deposit: { amount: 6000, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Ocean Vida desk', paymentMethod: 'Hotel charge', paidOffset: -4 },
  },
  {
    key: 'advanced-course-upcoming', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.WHATSAPP, createdOffset: -6,
    notes: 'Advanced course for two; deep and navigation are priorities.', internalNotes: 'Both have recent dives.', adminNotes: 'Two-day schedule approved.',
    participants: [{ customerKey: 'noah-fischer' }, { customerKey: 'nora-jensen' }],
    activities: [{ key: 'advanced', activityType: ActivityType.ADVANCED_OPEN_WATER_COURSE, dateOffset: 5, durationDays: 2, requestedTime: '07:00', timeSlot: ScheduleTimeSlot.AM, assignments: [erikLead] }],
    deposit: { amount: 5000, status: DepositStatus.PARTIALLY_PAID, currency: 'PESOS', paidTo: 'Front desk', paymentMethod: 'Bank transfer', paidOffset: -5 },
  },
  {
    key: 'solo-dsd-upcoming', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.EMAIL, createdOffset: -3,
    notes: 'I would like to try scuba before deciding about Open Water.', internalNotes: 'Solo DSD can join the afternoon session.', adminNotes: 'Approved pending balance at check-in.',
    participants: [{ customerKey: 'chloe-dubois', equipmentNeeded: 'Full equipment, size S' }],
    activities: [{ key: 'dsd', activityType: ActivityType.DISCOVER_SCUBA_DIVING, dateOffset: 6, requestedTime: '13:00', timeSlot: ScheduleTimeSlot.PM, assignments: [erikLead] }],
    deposit: { amount: 1000, status: DepositStatus.PARTIALLY_PAID, currency: 'PESOS', paidTo: 'Online', paymentMethod: 'Card', paidOffset: -2 },
  },
  {
    key: 'rescue-course-upcoming', status: BookingStatus.SCHEDULED, createdByEmail: 'manager@diveshop.local', source: BookingSource.INSTRUCTOR, createdOffset: -8, referrerName: 'Erik Instructor',
    notes: 'Rescue course after completing EFR at home.', internalNotes: 'EFR proof received by email.', adminNotes: 'Three training days scheduled.',
    participants: [{ customerKey: 'isabella-rossi' }, { customerKey: 'owen-brooks' }],
    activities: [{ key: 'rescue', activityType: ActivityType.RESCUE_DIVER_COURSE, dateOffset: 7, durationDays: 3, requestedTime: '08:00', timeSlot: ScheduleTimeSlot.AM, scheduleNotes: 'Scenario day on final day; prepare oxygen kit.', assignments: [erikLead, juniorDivemaster] }],
    deposit: { amount: 7000, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Front desk', paymentMethod: 'Card', paidOffset: -7 },
  },
  {
    key: 'tan-fun-dive-return', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.WHATSAPP, createdOffset: -2,
    notes: 'One fun-dive morning before departure.', internalNotes: 'Returning course customers.', adminNotes: 'Approved; rental equipment from course retained.',
    participants: [{ customerKey: 'daniel-tan' }, { customerKey: 'mei-lin-tan' }],
    activities: [{ key: 'fun-dive', activityType: ActivityType.FUN_DIVE, dateOffset: 8, requestedTime: '07:00', timeSlot: ScheduleTimeSlot.AM, assignments: [markLead] }],
    deposit: { amount: 3000, status: DepositStatus.PENDING, currency: 'PESOS', dueOffset: 6, notes: 'Pay at the shop by the day before.' },
  },
  {
    key: 'sunset-snorkeling', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.WALK_IN, createdOffset: -1,
    notes: 'Easy snorkeling trip for two non-divers.', internalNotes: 'Afternoon tide preferred.', adminNotes: 'Boat space confirmed.',
    participants: [{ customerKey: 'olivia-martin' }, { customerKey: 'ethan-martin' }],
    activities: [{ key: 'snorkeling', activityType: ActivityType.SNORKELING, dateOffset: 9, requestedTime: '15:30', timeSlot: ScheduleTimeSlot.PM, assignments: [rigieGuide] }],
    deposit: { amount: 1000, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Reception', paymentMethod: 'Cash', paidOffset: -1 },
  },
  {
    key: 'future-sidemount-course', status: BookingStatus.SCHEDULED, createdByEmail: 'admin@diveshop.local', source: BookingSource.EMAIL, createdOffset: -4,
    notes: 'Sidemount course before a technical diving trip.', internalNotes: 'Customer bringing wing and harness.', adminNotes: 'Two days scheduled with Mark.',
    participants: [{ customerKey: 'maria-garcia', equipmentNeeded: 'Twin cylinders and sidemount regulators' }],
    activities: [{ key: 'sidemount', activityType: ActivityType.SPECIALTY_COURSE, specialtyCourse: 'Sidemount Diver', dateOffset: 10, durationDays: 2, requestedTime: '08:00', timeSlot: ScheduleTimeSlot.AM, assignments: [markLead] }],
    deposit: { amount: 4000, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Online', paymentMethod: 'Card', paidOffset: -3 },
  },
  {
    key: 'solo-fun-dive-next-week', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.EMAIL, createdOffset: -1,
    notes: 'Experienced solo traveler looking to join a group.', internalNotes: 'Can join existing morning boat.', adminNotes: 'Certification and insurance checked.',
    participants: [{ customerKey: 'yuki-nakamura' }],
    activities: [{ key: 'fun-dive', activityType: ActivityType.FUN_DIVE, dateOffset: 11, requestedTime: '06:00', timeSlot: ScheduleTimeSlot.AM, assignments: [markLead, juniorDivemaster] }],
    deposit: { amount: 1800, status: DepositStatus.PENDING, currency: 'PESOS', dueOffset: 8 },
  },
  {
    key: 'efr-course', status: BookingStatus.SCHEDULED, createdByEmail: 'manager@diveshop.local', source: BookingSource.PHONE, createdOffset: -3,
    notes: 'EFR course needed before Rescue Diver certification.', internalNotes: 'Classroom setup only; no equipment rental.', adminNotes: 'Afternoon classroom slot approved.',
    participants: [{ customerKey: 'priya-nair' }, { customerKey: 'alex-kim' }],
    activities: [{ key: 'efr', activityType: ActivityType.EMERGENCY_FIRST_RESPONSE, dateOffset: 12, requestedTime: '13:00', timeSlot: ScheduleTimeSlot.PM, assignments: [erikLead] }],
    deposit: { amount: 2000, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Front desk', paymentMethod: 'Cash', paidOffset: -2 },
  },
  {
    key: 'future-open-water-course', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.WECHAT, createdOffset: -2,
    notes: '两位学生已完成在线学习，希望三天完成课程。', internalNotes: 'Chinese-language briefings requested; arrange translated knowledge review.', adminNotes: 'Course scheduled through the two-week horizon.',
    participants: [{ customerKey: 'li-wei', equipmentNeeded: 'Full equipment, size M' }, { customerKey: 'zhang-min', equipmentNeeded: 'Full equipment, size S' }],
    activities: [{ key: 'open-water', activityType: ActivityType.OPEN_WATER_COURSE, dateOffset: 12, durationDays: 3, requestedTime: '08:00', timeSlot: ScheduleTimeSlot.AM, scheduleNotes: 'Ends on day +14; translated materials prepared.', assignments: [erikLead, rigieGuide] }],
    deposit: { amount: 2400, status: DepositStatus.PARTIALLY_PAID, currency: 'YUAN', paidTo: 'WeChat Pay', paymentMethod: 'WeChat Pay', paidOffset: -1 },
  },
  {
    key: 'unassigned-horizon-fun-dive', status: BookingStatus.SCHEDULED, createdByEmail: 'cs@diveshop.local', source: BookingSource.WHATSAPP, createdOffset: 0,
    notes: 'Two-tank fun dive at the end of our stay.', internalNotes: 'Operational follow-up: instructor assignment still needed.', adminNotes: 'Approved; leave unassigned for scheduling queue demo.',
    participants: [{ customerKey: 'felix-muller' }],
    activities: [{ key: 'fun-dives', activityType: ActivityType.FUN_DIVE, dateOffset: 14, requestedTime: '06:30', timeSlot: ScheduleTimeSlot.AM, scheduleNotes: 'Instructor not assigned yet.', assignments: [] }],
    deposit: { amount: 1800, status: DepositStatus.PENDING, currency: 'PESOS', dueOffset: 11 },
  },
  {
    key: 'pending-fun-dive', status: BookingStatus.PENDING_APPROVAL, createdByEmail: 'cs@diveshop.local', source: BookingSource.WHATSAPP, createdOffset: -1,
    notes: 'Can I join two fun dives later this week?', internalNotes: 'Certification submitted; awaiting admin review.',
    participants: [{ customerKey: 'alex-kim' }],
    activities: [{ key: 'fun-dive', activityType: ActivityType.FUN_DIVE, dateOffset: 4, requestedTime: '07:00', timeSlot: ScheduleTimeSlot.AM }],
    deposit: { status: DepositStatus.PENDING, currency: 'PESOS', dueOffset: 2 },
  },
  {
    key: 'pending-dsd-group', status: BookingStatus.PENDING_APPROVAL, createdByEmail: 'cs@diveshop.local', source: BookingSource.WECHAT, createdOffset: 0,
    notes: '三个人想一起体验潜水，上午可以。', internalNotes: 'New WeChat inquiry entered by customer service; forms complete.',
    participants: [{ customerKey: 'chen-yu' }, { customerKey: 'zhang-min' }, { customerKey: 'li-wei' }],
    activities: [{ key: 'dsd', activityType: ActivityType.DISCOVER_SCUBA_DIVING, dateOffset: 9, requestedTime: '09:00', timeSlot: ScheduleTimeSlot.AM }],
    deposit: { amount: 1200, status: DepositStatus.PARTIALLY_PAID, currency: 'YUAN', paidTo: 'WeChat Pay', paymentMethod: 'WeChat Pay', paidOffset: 0 },
  },
  {
    key: 'pending-deep-specialty', status: BookingStatus.PENDING_APPROVAL, createdByEmail: 'manager@diveshop.local', source: BookingSource.INSTRUCTOR, createdOffset: 0, referrerName: 'Mark Instructor',
    notes: 'Deep Diver specialty during the second week.', internalNotes: 'All prerequisite information received; manager review pending.',
    participants: [{ customerKey: 'nora-jensen' }],
    activities: [{ key: 'deep-diver', activityType: ActivityType.SPECIALTY_COURSE, specialtyCourse: 'Deep Diver', dateOffset: 14, durationDays: 2, requestedTime: '07:00', timeSlot: ScheduleTimeSlot.AM }],
    deposit: { amount: 2500, status: DepositStatus.PAID, currency: 'PESOS', paidTo: 'Mark Instructor', paymentMethod: 'Bank transfer', paidOffset: 0 },
  },
  {
    key: 'needs-info-certification', status: BookingStatus.NEEDS_MORE_INFO, createdByEmail: 'cs@diveshop.local', source: BookingSource.EMAIL, createdOffset: -2,
    notes: 'I would like to do fun dives next weekend.', internalNotes: 'Customer profile created from email inquiry.', needsMoreInfoReason: 'Please provide the certification agency, certification level, and a photo of the certification card before resubmitting.',
    participants: [{ customerKey: 'samir-patel', certificationAgency: '', certificationLevel: '', divesLogged: 0 }],
    activities: [{ key: 'fun-dive', activityType: ActivityType.FUN_DIVE, dateOffset: 3, requestedTime: '07:00', timeSlot: ScheduleTimeSlot.AM }],
    deposit: { status: DepositStatus.UNKNOWN },
  },
  {
    key: 'needs-info-medical', status: BookingStatus.NEEDS_MORE_INFO, createdByEmail: 'cs@diveshop.local', source: BookingSource.WHATSAPP, createdOffset: -1,
    notes: 'Open Water course next week if space is available.', internalNotes: 'Medical questionnaire has a positive response.', needsMoreInfoReason: 'A physician-signed medical clearance is required before this course can be approved.',
    participants: [{ customerKey: 'olivia-martin', equipmentNeeded: 'Full equipment, size S' }],
    activities: [{ key: 'open-water', activityType: ActivityType.OPEN_WATER_COURSE, dateOffset: 11, durationDays: 3, requestedTime: '08:00', timeSlot: ScheduleTimeSlot.AM }],
    deposit: { amount: 1000, status: DepositStatus.PARTIALLY_PAID, currency: 'PESOS', paidTo: 'Online', paymentMethod: 'Card', paidOffset: -1, notes: 'Hold until medical clearance is received.' },
  },
  {
    key: 'draft-phone-inquiry', status: BookingStatus.DRAFT, createdByEmail: 'cs@diveshop.local', source: BookingSource.PHONE, createdOffset: 0,
    notes: 'Caller asked about beginner options and will confirm travel dates.', internalNotes: 'Draft intake; follow up in two days.',
    participants: [{ customerKey: 'owen-brooks' }],
    activities: [{ key: 'dsd', activityType: ActivityType.DISCOVER_SCUBA_DIVING, dateOffset: 7, timeSlot: ScheduleTimeSlot.TBD }],
  },
  {
    key: 'draft-wechat-inquiry', status: BookingStatus.DRAFT, createdByEmail: 'cs@diveshop.local', source: BookingSource.WECHAT, createdOffset: 0,
    notes: '咨询潜水课程，还没有确定酒店。', internalNotes: 'Waiting for flight and hotel details.',
    participants: [{ customerKey: 'li-wei' }],
    activities: [{ key: 'advanced', activityType: ActivityType.ADVANCED_OPEN_WATER_COURSE, dateOffset: 13, durationDays: 2, timeSlot: ScheduleTimeSlot.TBD }],
    deposit: { status: DepositStatus.UNKNOWN },
  },
  {
    key: 'cancelled-weather-history', status: BookingStatus.CANCELLED, createdByEmail: 'cs@diveshop.local', source: BookingSource.WALK_IN, createdOffset: -17, preserveCancelledSchedule: true,
    notes: 'Morning fun dive booking.', internalNotes: 'Trip cancelled because boats were held in port.', adminNotes: 'Cancelled due to unsafe sea conditions; deposit refunded.',
    participants: [{ customerKey: 'isabella-rossi' }],
    activities: [{ key: 'fun-dive', activityType: ActivityType.FUN_DIVE, dateOffset: -15, requestedTime: '06:00', timeSlot: ScheduleTimeSlot.AM, assignments: [markLead] }],
    deposit: { amount: 1800, status: DepositStatus.REFUNDED, currency: 'PESOS', paidTo: 'Front desk', paymentMethod: 'Card', paidOffset: -16, notes: 'Refunded to original card.' },
  },
  {
    key: 'cancelled-travel-change', status: BookingStatus.CANCELLED, createdByEmail: 'cs@diveshop.local', source: BookingSource.EMAIL, createdOffset: -3,
    notes: 'Two-person DSD request.', internalNotes: 'Guests changed their island itinerary.', adminNotes: 'Cancelled by guest before approval; no deposit collected.',
    participants: [{ customerKey: 'grace-ong' }, { customerKey: 'tom-ong' }],
    activities: [{ key: 'dsd', activityType: ActivityType.DISCOVER_SCUBA_DIVING, dateOffset: 5, requestedTime: '13:00', timeSlot: ScheduleTimeSlot.PM }],
    deposit: { status: DepositStatus.WAIVED, notes: 'Cancelled before payment deadline.' },
  },
];
