ALTER TABLE "BookingActivity"
ADD COLUMN "durationDays" INTEGER NOT NULL DEFAULT 1;

UPDATE "BookingActivity"
SET "durationDays" = CASE "activityType"
  WHEN 'OPEN_WATER_COURSE' THEN 3
  WHEN 'ADVANCED_OPEN_WATER_COURSE' THEN 2
  WHEN 'RESCUE_DIVER_COURSE' THEN 3
  ELSE 1
END;
